version: 2.1

orbs:
  mytest:
    jobs:
      env:
        machine:
          image: ubuntu-1604:202007-01
        steps:
          - run:
              name: echo env
              command: echo $K8S_CREDENTIALS_JSON

jobs:
  chk:
    docker:
      - image: 'mcr.microsoft.com/dotnet/sdk:5.0'
    steps:
      - checkout
      - run:
          name: ls
          command: ls -lah

workflows:
  main:
    jobs:
      - mytest/env:
          context:
            test
