version: 2.1

jobs:
  chk:
    docker:
      - image: 'mcr.microsoft.com/dotnet/sdk:5.0'
    steps:
      - checkout
      - run:
          name: ls
          command: ls -lah

workflows:
  main:
    jobs:
      - chk
